apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: url-shortener
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: url-shortener
  template:
    metadata:
      labels:
        io.kompose.service: url-shortener
    spec:
      containers:
        - image: cjhjrnsczxj/url-shortener:0.0.2
          name: url-shortener
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: url-shortener
  name: url-shortener
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: url-shortener
